### PR TITLE
Embedded google group

### PR DESCRIPTION
**Pull request by franklin-feingold**
Embedded the google group
Added a space between the bids contributor guide hyperlink and 'Please adhere to our Code of Conduct'

### CODE REVIEW

**Comment by chrisfilo** [comment]
The mailing list embedding does not render when I open index.html file locally. How did you tested it?

**Comment by franklin-feingold** [comment]
Unfortunately the frame will not render the google group locally.  The url embedded in the iframe had a parameter called 'parenturl'. The parenturl has to match the domain that the document with the iframe is being served from. When tested locally the url for local files on our computers is weird and the browsers didn't like it when they cross checked the origin I believe. 
For testing, I opened it from my github repo (https://franklin-feingold.github.io/BIDS/). From there I saw that the webpage displays the embedded google group.

**Comment by chrisfilo** [comment]
Thanks!

image
could you fix the styling?

**Comment by franklin-feingold** [comment]
I added a white background fill behind the embedded google group to improve the contrast. It looks better and can see the different posts more clearly. 

bids_google_group_white_background

**Comment by chrisfilo** [comment]
Awesome! Thanks!

**Pull request merged**
